[advisories]
version = 2
yanked = "deny"

[licenses]
version = 2
unused-allowed-license = "allow"
allow = [
  "Apache-2.0",
  "MIT",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
